app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,RadioField
from wtforms.validators import Required

class PitchForm(FlaskForm):

    title=StringField('Pitch title', validators=[Required()])
    category=RadioField('Label',choices=[('investorpitch','investorpitch'),('productpitch','productpitch'),('interviewpitch','interviewpitch'),('marketpitch','marketpitch')],validators=[Required()])
    description=TextAreaField('Enter your pitch', validators=[Required()])
    submit=SubmitField('Submit')

class CommentForm(FlaskForm):
    description=TextAreaField('Leave a comment')
    submit=SubmitField()

class UpvoteForm(FlaskForm):
    submit=SubmitField()

class DownvoteForm(FlaskForm):
    submit=SubmitField()

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from  flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail
from flask_simplemde import SimpleMDE

login_manager=LoginManager()
login_manager.session_protection='strong'
login_manager.login_view='auth.login'
mail=Mail()
simple = SimpleMDE()


bootstrap = Bootstrap()
db = SQLAlchemy()

photos=UploadSet('photos',IMAGES)

def create_app(config_name):

    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)

    # registering the blue print
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    # #setting config
    # from.request import configure_request
    # configure_request(app)

    from.auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix='/auth')

    # configure UploadSet
    configure_uploads(app,photos)

    #mail
    mail.init_app(app)

    #simple mde
    simple.init_app(app)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main', __name__)
from . import views,error

app/main/views.py
from flask import render_template,request,redirect,url_for,abort,flash
from . import main
from .forms import PitchForm,CommentForm,UpvoteForm,DownvoteForm,UpdateProfile
from flask_login import login_required,current_user
from flask.views import View, MethodView
from ..model import User,Pitch,Comment,Downvote,Upvote
from ..import db,photos
import markdown2

@main.route('/', methods=['GET','POST'])
def index():
    pitch=Pitch.query.filter_by().first()

    title='Pitch Zone'

    investorpitch=Pitch.query.filter_by(category="investorpitch")
    productpitch=Pitch.query.filter_by(category="productpitch")
    interviewpitch=Pitch.query.filter_by(category="interviewpitch")
    marketpitch=Pitch.query.filter_by(category="marketpitch")

    upvotes=Upvote.get_all_upvotes(pitch_id=Pitch.id)

    return render_template('root.html',title=title,investorpitch=investorpitch,productpitch=productpitch,interviewpitch=interviewpitch,marketpitch=marketpitch,upvotes=upvotes)


@main.route('/pitch/new', methods=['GET','POST'])
@login_required
def make_pitch():

    form =PitchForm()
    available_upvotes=Upvote.query.filter_by(pitch_id = Pitch.id)
    if form.validate_on_submit(): 

        owner_id = current_user
        category = form.category.data
        description = form.description.data
        title = form.title.data
        print(current_user._get_current_object().id)
        make_pitch = Pitch(owner_id =current_user._get_current_object().id, title = title,description=description,category=category)
        db.session.add(make_pitch)
        db.session.commit()
        
        
        return redirect(url_for('main.index'))
    return render_template('pitch.html',form=form)


@main.route('/comment/new/<int:pitch_id>', methods = ['GET','POST'])
@login_required
def make_comment(pitch_id):
    form = CommentForm()
    pitch=Pitch.query.get(pitch_id)
    if form.validate_on_submit():
        description = form.description.data

        make_comment = Comment(description = description, user_id = current_user._get_current_object().id, pitch_id = pitch_id)
        db.session.add(make_comment)
        db.session.commit()


        return redirect(url_for('.make_comment', pitch_id= pitch_id))

    all_comments = Comment.query.filter_by(pitch_id = pitch_id).all()
    return render_template('comment.html', form = form, comment = all_comments, pitch = pitch )


@main.route('/pitch/upvote/<int:pitch_id>/upvote', methods = ['GET', 'POST'])
@login_required
def make_upvote(pitch_id):
    pitch = Pitch.query.get(pitch_id)
    user = current_user
    pitch_upvotes = Upvote.query.filter_by(pitch_id= pitch_id)
    
    if Upvote.query.filter(Upvote.user_id==user.id,Upvote.pitch_id==pitch_id).first():
        return  redirect(url_for('main.index'))
    
    made_upvote = Upvote(pitch_id=pitch_id, user = current_user)
    made_upvote.save_upvotes()
    return redirect(url_for('main.index'))

@main.route('/pitch/downvote/<int:pitch_id>/downvote', methods = ['GET', 'POST'])
@login_required
def make_downvote(pitch_id):
    pitch = Pitch.query.get(pitch_id)
    user = current_user
    pitch_downvotes = Downvote.query.filter_by(pitch_id= pitch_id)
    
    if Downvote.query.filter(Downvote.user_id==user.id,Downvote.pitch_id==pitch_id).first():
        return  redirect(url_for('main.index'))

    made_downvote = Downvote(pitch_id=pitch_id, user = current_user)
    made_downvote.save_downvotes()
    return redirect(url_for('main.index'))


@main.route('/user/<uname>')
def profile(uname):
    user=User.query.filter_by(username=uname).first()
    pitcheslist=Pitch.get_pitches(current_user.id)

    if user is None:
        abort (404)

    return render_template("profile/profile.html",user=user,pitcheslist=pitcheslist)

@main.route('/user/<uname>/update', methods=['GET','POST'])
@login_required

def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort (404)

    form=UpdateProfile()

    if form.validate_on_submit():
        user.bio=form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form=form)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

app/templates/base.html
{% extends 'bootstrap/base.html'%}

<!-- Navbar block  --> 
{% block navbar %}

    {% include 'navbar.html' %}
    
{% endblock %}

{%block styles %}
  {{super()}}
  <!--Importing the simple mde css and js files  -->
  {{ simplemde.css}}
  {{ simplemde.js }}

{% endblock %}

app/templates/comment.html
{% include 'navbar.html'%}

{% import 'bootstrap/wtf.html' as wtf %}
{% extends 'bootstrap/base.html' %}
{% import 'macros.html' as macro %}

{% block content %}




<div class="row">
        <div class="card" >
                <div class="card-body text-center">
                        <h4><a style="font-size: 40px;">{{pitch.title}}</a></h4>
                        <h5 class="card-text text-center" style="font-size: 20px;">{{pitch.description}}.</h5>
                </div>
        </div>


        <div class="container">
                <div class="row">
                        <div class="jumbotron">
                                {{wtf.quick_form(form)}}
                        </div>
                </div>
        </div>

        <hr>
        <hr>
        <div class="container"style=" border:2px double rgb(26, 123, 214);border-radius: 15px 50px 30px 5px; margin-top: 20px;">
                <div>
                        <h4 style="color:rgb(26, 123, 214); text-align: center; font-size: 30px;">Comments</h4>
                      <h4 style="font-size: 30px;">{{ macro.displayComments(comment) }}</h4>  

                </div>

        </div>

</div>




{% endblock %}

app/templates/fourOwfour.html
{% extends 'base.html' %}

{% block content%}
<h1>WHOOOPS we can't find that page</h1>
{% endblock %}

app/templates/macros.html
{% macro displayPitchCategory(pitch_list)%}
<div class="row">
	{% if pitch_list %}
	{% for pitch in pitch_list %}
	<div class="col-md-6">
		<div class="thumbnail text-center" style="background: transparent; color: white;" >
			<h5 class="card-header" style="font-size: 40px;">Title: {{pitch.title}}</h5>
			<h5 class="card-header" style="font-size: 40px;">Category: {{pitch.category}}</h5>
			<div class="card-body">
				<blockquote class="blockquote mb-0">
					<h2>{{pitch.description}}</h2>
					<footer class="blockquote-footer" style="font-size: 40px;"> Posted by {{pitch.user.username}}</footer>
				</blockquote>

				<a href="{{url_for('main.make_comment',pitch_id = pitch.id)}}" class="btn btn-success" style="font-size: 20px;"> Add a comment</a>
				<a href="{{url_for('main.make_upvote',pitch_id = pitch.id)}}"
					class="btn btn-warning btn-sm" style="font-size: 30px;"><i></i>Upvote <span>{{pitch.upvotes.count()}}</span></a>

				<a href="{{url_for('main.make_downvote',pitch_id = pitch.id)}}"
				class="btn btn-danger btn-sm" style="font-size: 30px;"><i></i>Downvote <span>{{pitch.upvotes.count()}}</span></a>
<!-- 
				<a href="{{url_for('main.make_downvote',pitch_id = pitch.id)}}" class="btn btn-danger btn-sm"><i></i>Downvote <span>{{pitch.downvotes.count()}}</span></a>
						class="far fa-thumbs-up" style="font-size: 30px;"> -->
			</div>
		</div>

	</div>
	{% endfor %}
	{% else %}
	{% endif %}z
</div>

{% endmacro%}

<!-- Displaying comments macro -->
{% macro displayComments(comment_list) %}
<ul>

	{% if comment_list %}
	{% for comment in comment_list %}
	<div class="row text-center">
		<a>
			<p style="color: brown">{{ comment.description }}</p>
		</a>
		<small> posted by {{comment.user.username}}</small>
	</div>
	{% endfor %}
	{% else %}

	<h3>This post does not does not have any comments yet !</h3>
	{%endif%}

</ul>

{% endmacro %}

app/templates/navbar.html
<div class="navbar navbar-expand-lg navbar-light bg-light" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/" style="font-size: 90%;color:black;">Pitch Zone</a>
            <a class="navbar-brand" href="/pitch/new" style="font-size: 90%;">Make pitch</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav navbar-right" style="font-size: 90%;">
                {%if current_user.is_authenticated%}
                <li><a style="color:black;">Current user: {{current_user.username}}</a></li>
                <li><a style="color:black;"href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
                <li><a style="color:black;"href="{{url_for('auth.logout')}}">Sign out</a></li>
                {%else%}
                <li><a style="color:black; border:1px solid black;"href="{{url_for('auth.login')}}">Sign in</a></li>
                {%endif%}
            </ul>
        </div>
    </div>
</div>

app/templates/pitch.html
{% import 'bootstrap/wtf.html' as wtf %}
{% extends 'bootstrap/base.html' %}
{% include 'navbar.html'%}

{% block content %}
<div class="container" style="background: linear-gradient(to right, #ef8e38, #108dc7); width:70%;height:80%; font-size:30px;">
	<div class="row" >
		<div class="jumbotron" style="background: transparent;">
			{{wtf.quick_form(form)}}
			<ul style="list-style: none;background: transparent;">
				{% for pitch in pitches %}
				<div class="list-group" style="background: transparent;">
					<a href="#">
						<div class="list-item" style="background: transparent;">
							<p>{{pitch.id}}</p>
						</div>
						<h4>{{ pitch.description }}</h4>
						<h6> Posted by {{user.username}}.</h6>
					</a>
				</div>
				{% endfor %}
			</ul>
		</div>
	</div>
</div>

{% endblock %}

app/templates/profile/profile.html
{% extends 'bootstrap/base.html' %}

{% block navbar %}
{% include 'navbar.html'%}
{% endblock %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename='css/profile.css')}}">
<link href="https://fonts.googleapis.com/css?family=Marck+Script&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Courgette&display=swap" rel="stylesheet">
{% endblock %}

</head>
<body>
        {% block content %}
        <div class="container" >
            <div class="row" style="font-size: 30px;">
                <!-- displaying Username -->
                <div class ="col-md-4">
                    <h3 style="text-transform: uppercase; font-family: 'Courgette', cursive;"><b>{{user.username}} PROFILE</b></h3>
        
                <!-- Displaying user bio -->
                {%if user.bio%}
                <p>{{user.bio}}</p>
                {%else%}
                <p>{{user.username|capitalize}} has no bio</p>
                {%endif%}
                
                {% if user == current_user %}
                <a style="font-family: 'Courgette', cursive;" href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
                {% endif %}
        
                </div>
        
                <!-- Displaying profile photo -->
                <div class="col-md-4"style="font-family: 'Courgette', cursive;" >
                    {%if user.profile_pic_path%}
                    <img src ="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class ="img-thumbnail">
                    {%else%}
                    <p>No profile picture</p>
                    {%endif%}
        
                    {%if user==current_user%}
                    <form  action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype = "multipart/form-data">
                        <input type="file" name="photo" class="form-control" required>
                        <input type="submit">
                    </form>
                    {%endif%}
                
                
                </div><br><br>

                <div class="row" style="font-family: 'Courgette', cursive;" >
                    <div class="col-sm-6" style="border:2px double black;border-radius: 15px 50px 30px 5px; margin-top: 20px;">
                            <h3 style="text-transform: uppercase;" class="card-title"><b>{{current_user.username}} PITCHES</b></h3>
                            {%for pitch in pitcheslist%}
                            <h3><i><b>Category: {{pitch.category}}</b></i></h3>
                            <h3>Title: {{pitch.title}}</h3>
                            <h3 class="card-text">Pitch: {{pitch.description}}</h3>
                            {%endfor%}
                    </div>
                    
                </div>
               
        
                
            </div>
        </div>
        {%endblock%}
    
</body>
</html>

app/templates/profile/update.html
{%extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf%}

{%block content%}
<div class ="container">
    {{wtf.quick_form(form)}}
</div>
{%endblock%}

app/templates/root.html
{% extends 'bootstrap/base.html' %}
{% import 'macros.html' as macro %}

{% block navbar %}
{% include 'navbar.html'%}
{% endblock %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static', filename='css/root.css')}}">
<link href="https://fonts.googleapis.com/css?family=Marck+Script&display=swap" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Odibee+Sans&display=swap" rel="stylesheet">
{% endblock %}

</head>
<body>
  
{% block content %}
<div class="container">
  <h3 style="color: green;text-align: center;font-size: 40px; text-transform: uppercase;font-family: Georgia, 'Times New Roman', Times, serif;">Click a category to view pitches </h3>
  <br>
  <ul class="nav nav-pills nav-justified nav-fill" role="tablist">
    <li class="nav-item">
      <a class="nav-link active" data-toggle="tab" href="#investment">Investment</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#product">Product</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#interview">Interview</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" data-toggle="tab" href="#market">Market</a>
    </li>
  </ul>

  <div class="tab-content">
    <div id="investment" class="container tab-pane active"><br>
      {{ macro.displayPitchCategory(investorpitch) }}

    </div>
    <div id="product" class="container tab-pane fade"><br>
      {{ macro.displayPitchCategory(productpitch) }}
    </div>
    <div id="interview" class="container tab-pane fade"><br>
      {{ macro.displayPitchCategory(interviewpitch)}}
    </div>
    <div id="market" class="container tab-pane fade"><br>
      {{ macro.displayPitchCategory(marketpitch) }}
    </div>

  </div>
</div>
{% endblock %}
</body>
</html>